# Site settings
title: Domino Admin Community College
description: A prototype for Domino education
keywords: Modern, Blogging, Fun
author: Nadun
baseurl: "/Jekyll-Modern-Blog" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
gems: [jekyll-paginate,jekyll-seo-tag,jekyll-sitemap]
paginate: 3
google_analytics: 'UA-XXXXXXX-X'
